//! FTP / FTPS client backed by the `suppaftp` crate.
//!
//! FTP returns directory listings as raw `LIST` output. [`parse_list_line`] is a
//! best-effort parser that recognises Unix (`ls -l`), Windows/DOS (IIS), and
//! OpenVMS formats; unrecognised lines are skipped.
//! The `RemoteFs` implementation is generated by [`impl_ftp_remotefs`] so plain
//! FTP and FTPS (in `ftps.rs`) share identical logic.

use std::io::Read;
use std::net::ToSocketAddrs;
use std::time::Duration;

use suppaftp::FtpStream;

use crate::error::{Error, Result};
use crate::models::{ConnectionRequest, DirEntry, EntryKind, FtpMode, LogonType};

/// Map our `FtpMode` to a suppaftp `Mode`. `None` means "leave the library
/// default" (passive), so callers only call `set_mode` when this returns `Some`.
pub(crate) fn ftp_mode_to_suppaftp(mode: Option<FtpMode>) -> Option<suppaftp::Mode> {
    match mode {
        Some(FtpMode::Active) => Some(suppaftp::Mode::Active),
        Some(FtpMode::Passive) => Some(suppaftp::Mode::Passive),
        _ => None,
    }
}

/// FTP transfer representation (FileZilla "Transfer type").
#[derive(Clone, Copy, PartialEq, Eq)]
pub(crate) enum FtpDataType {
    /// Pick ASCII for known text extensions, otherwise binary.
    Auto,
    Ascii,
    Binary,
}

/// Parse the wire value of the transfer-type preference (default: Auto).
pub(crate) fn parse_data_type(s: Option<&str>) -> FtpDataType {
    match s {
        Some("ascii") => FtpDataType::Ascii,
        Some("binary") => FtpDataType::Binary,
        _ => FtpDataType::Auto,
    }
}

/// Extensions transferred as ASCII text in Auto mode (newline translation).
const ASCII_EXTS: &[&str] = &[
    "txt", "html", "htm", "css", "js", "json", "xml", "csv", "md", "ini", "cfg", "conf", "log",
    "sh", "py", "rb", "pl", "php", "c", "h", "cpp", "java", "rs", "go", "yml", "yaml", "toml",
    "sql", "svg", "tex",
];

/// Resolve the suppaftp `FileType` to use for `path` under the given mode.
///
/// When `resume` is set we force binary: ASCII transfers apply newline
/// translation, so a byte offset (`REST`) no longer aligns with the file and
/// resuming in ASCII would corrupt it. (FileZilla likewise disables ASCII resume.)
pub(crate) fn resolve_file_type(
    mode: FtpDataType,
    path: &str,
    resume: bool,
) -> suppaftp::types::FileType {
    use suppaftp::types::{FileType, FormatControl};
    if resume {
        return FileType::Binary;
    }
    let ascii = match mode {
        FtpDataType::Ascii => true,
        FtpDataType::Binary => false,
        FtpDataType::Auto => {
            let ext = path
                .rsplit('/')
                .next()
                .and_then(|n| n.rsplit_once('.'))
                .map(|(_, e)| e.to_ascii_lowercase());
            ext.is_some_and(|e| ASCII_EXTS.contains(&e.as_str()))
        }
    };
    if ascii {
        FileType::Ascii(FormatControl::Default)
    } else {
        FileType::Binary
    }
}

/// Rewrite the login username for the "USER user@host" FTP proxy style. With no
/// FTP proxy in use (`via_proxy == false`) the username is returned unchanged.
fn proxy_user(user: &str, host: &str, port: u16, via_proxy: bool) -> String {
    if !via_proxy {
        user.to_string()
    } else if port == 21 {
        format!("{user}@{host}")
    } else {
        format!("{user}@{host}:{port}")
    }
}

pub struct FtpClient {
    pub(crate) inner: FtpStream,
    pub(crate) data_type: FtpDataType,
}

impl FtpClient {
    /// Connect and log in. `_explicit_tls` is reserved; FTPS lives in `ftps.rs`.
    pub fn connect(req: &ConnectionRequest, _explicit_tls: bool) -> Result<Self> {
        let timeout = Duration::from_secs(req.timeout_secs.unwrap_or(20));
        // Legacy FTP-protocol proxy ("USER user@host"): when configured we connect
        // to the proxy's address instead of the server, and rewrite the username.
        let ftp_proxy = req
            .ftp_proxy_host
            .as_deref()
            .filter(|h| !h.trim().is_empty())
            .map(|h| (h.to_string(), req.ftp_proxy_port.unwrap_or(21)));
        let connect_host = ftp_proxy
            .as_ref()
            .map(|(h, _)| h.clone())
            .unwrap_or_else(|| req.host.clone());
        let connect_port = ftp_proxy.as_ref().map(|(_, p)| *p).unwrap_or(req.port);

        let mut inner = match req
            .proxy
            .as_ref()
            .filter(|p| p.kind != crate::models::ProxyType::None)
        {
            Some(proxy) => {
                let tcp =
                    super::proxy::connect_via_proxy(proxy, &connect_host, connect_port, timeout)?;
                FtpStream::connect_with_stream(tcp).map_err(|e| Error::Connection(e.to_string()))?
            }
            None => {
                let addr = format!("{connect_host}:{connect_port}");
                let sock = addr
                    .to_socket_addrs()
                    .map_err(|e| Error::Connection(format!("cannot resolve {connect_host}: {e}")))?
                    .next()
                    .ok_or_else(|| Error::Connection(format!("no address for {connect_host}")))?;
                FtpStream::connect_timeout(sock, timeout)
                    .map_err(|e| Error::Connection(e.to_string()))?
            }
        };
        let via_proxy = ftp_proxy.is_some();
        let (user, pass) = match req.logon_type {
            LogonType::Anonymous => (
                proxy_user("anonymous", &req.host, req.port, via_proxy),
                String::new(),
            ),
            _ => (
                proxy_user(&req.username, &req.host, req.port, via_proxy),
                req.password.clone().unwrap_or_default(),
            ),
        };
        inner
            .login(&user, &pass)
            .map_err(|e| Error::Auth(e.to_string()))?;
        if let Some(m) = ftp_mode_to_suppaftp(req.ftp_mode) {
            inner.set_mode(m);
        }
        Ok(Self {
            inner,
            data_type: parse_data_type(req.ftp_data_type.as_deref()),
        })
    }
}

/// A `Read` adapter that reports progress as bytes flow through it (used for uploads).
pub(crate) struct ProgressReader<'a, R: Read> {
    pub inner: R,
    pub done: u64,
    pub total: u64,
    pub cb: &'a mut (dyn FnMut(u64, u64) -> bool + Send + 'a),
}

impl<'a, R: Read> Read for ProgressReader<'a, R> {
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        let n = self.inner.read(buf)?;
        if n > 0 {
            self.done += n as u64;
            // A `false` from the progress callback means "cancelled": report EOF
            // so the upload stops early (the worker finalizes it as Cancelled).
            if !(self.cb)(self.done, self.total) {
                return Ok(0);
            }
        }
        Ok(n)
    }
}

/// Generate a [`RemoteFs`] implementation for a type with a `.inner` FTP stream.
#[macro_export]
macro_rules! impl_ftp_remotefs {
    ($t:ty) => {
        impl $crate::protocols::RemoteFs for $t {
            fn cwd(&mut self) -> $crate::error::Result<String> {
                self.inner
                    .pwd()
                    .map_err(|e| $crate::error::Error::Remote(e.to_string()))
            }

            fn list(&mut self, path: &str) -> $crate::error::Result<Vec<$crate::models::DirEntry>> {
                let lines = self
                    .inner
                    .list(Some(path))
                    .map_err(|e| $crate::error::Error::Remote(e.to_string()))?;
                let mut out: Vec<_> = lines
                    .iter()
                    .filter_map(|l| $crate::protocols::ftp::parse_list_line(l, path))
                    .collect();
                out.sort_by(|a, b| {
                    $crate::protocols::ftp::sort_key(a).cmp(&$crate::protocols::ftp::sort_key(b))
                });
                Ok(out)
            }

            fn download(
                &mut self,
                remote: &str,
                dest: &std::path::Path,
                resume: bool,
                progress: &mut $crate::protocols::traits::ProgressFn,
            ) -> $crate::error::Result<()> {
                use std::io::{Seek, SeekFrom};
                // Pick ASCII vs binary representation for this file.
                let ft = $crate::protocols::ftp::resolve_file_type(self.data_type, remote, resume);
                let _ = self.inner.transfer_type(ft);
                let total = self.inner.size(remote).unwrap_or(0) as u64;
                let existing = if resume {
                    std::fs::metadata(dest).map(|m| m.len()).unwrap_or(0)
                } else {
                    0
                };
                if existing > 0 && existing >= total {
                    return Ok(()); // already complete
                }
                if existing > 0 {
                    self.inner
                        .resume_transfer(existing as usize)
                        .map_err(|e| $crate::error::Error::Remote(e.to_string()))?;
                }
                let mut file = if existing > 0 {
                    let mut f = std::fs::OpenOptions::new().write(true).open(dest)?;
                    f.seek(SeekFrom::Start(existing))?;
                    f
                } else {
                    std::fs::File::create(dest)?
                };
                let mut done: u64 = existing;
                self.inner
                    .retr(remote, |reader| {
                        let mut buf = [0u8; 64 * 1024];
                        loop {
                            let n = reader
                                .read(&mut buf)
                                .map_err(suppaftp::FtpError::ConnectionError)?;
                            if n == 0 {
                                break;
                            }
                            std::io::Write::write_all(&mut file, &buf[..n])
                                .map_err(suppaftp::FtpError::ConnectionError)?;
                            done += n as u64;
                            if !progress(done, total) {
                                break; // cancelled mid-stream
                            }
                        }
                        Ok(())
                    })
                    .map_err(|e| $crate::error::Error::Remote(e.to_string()))
            }

            fn upload(
                &mut self,
                src: &std::path::Path,
                remote: &str,
                resume: bool,
                progress: &mut $crate::protocols::traits::ProgressFn,
            ) -> $crate::error::Result<()> {
                use std::io::{Seek, SeekFrom};
                // Pick ASCII vs binary representation for this file.
                let ft = $crate::protocols::ftp::resolve_file_type(self.data_type, remote, resume);
                let _ = self.inner.transfer_type(ft);
                let total = std::fs::metadata(src)?.len();
                let existing = if resume {
                    self.inner.size(remote).map(|s| s as u64).unwrap_or(0)
                } else {
                    0
                };
                if existing > 0 && existing >= total {
                    return Ok(()); // already complete
                }
                if existing > 0 {
                    self.inner
                        .resume_transfer(existing as usize)
                        .map_err(|e| $crate::error::Error::Remote(e.to_string()))?;
                }
                let mut file = std::fs::File::open(src)?;
                if existing > 0 {
                    file.seek(SeekFrom::Start(existing))?;
                }
                let mut reader = $crate::protocols::ftp::ProgressReader {
                    inner: file,
                    done: existing,
                    total,
                    cb: progress,
                };
                self.inner
                    .put_file(remote, &mut reader)
                    .map(|_| ())
                    .map_err(|e| $crate::error::Error::Remote(e.to_string()))
            }

            fn keep_alive(&mut self) -> $crate::error::Result<()> {
                self.inner
                    .noop()
                    .map_err(|e| $crate::error::Error::Remote(e.to_string()))
            }

            fn disconnect(&mut self) -> $crate::error::Result<()> {
                let _ = self.inner.quit();
                Ok(())
            }
        }
    };
}

impl_ftp_remotefs!(FtpClient);

/// Stable sort: directories first, then case-insensitive name.
pub(crate) fn sort_key(e: &DirEntry) -> (u8, String) {
    let dir_first = if matches!(e.kind, EntryKind::Directory) {
        0
    } else {
        1
    };
    (dir_first, e.name.to_lowercase())
}

/// Parse a single Unix-style `LIST` line into a [`DirEntry`].
///
/// Example input: `-rw-r--r-- 1 john users 12600 May 10 08:11 styles.css`
/// Parse one `LIST` line, trying each known server format (Unix, then Windows/DOS,
/// then VMS). Returns `None` for headers, totals, `.`/`..`, or unrecognised lines.
pub(crate) fn parse_list_line(line: &str, parent: &str) -> Option<DirEntry> {
    parse_unix_line(line, parent)
        .or_else(|| parse_dos_line(line, parent))
        .or_else(|| parse_vms_line(line, parent))
}

/// Join a parent directory with a child name (remote paths use '/').
fn join_path(parent: &str, name: &str) -> String {
    if parent.ends_with('/') {
        format!("{parent}{name}")
    } else {
        format!("{parent}/{name}")
    }
}

/// Unix `ls -l` format: `drwxr-xr-x 2 owner group 4096 May 09 06:23 name`.
fn parse_unix_line(line: &str, parent: &str) -> Option<DirEntry> {
    let parts: Vec<&str> = line.split_whitespace().collect();
    if parts.len() < 9 {
        return None;
    }
    let perms = parts[0];
    // The first field must look like a Unix permission string, else this isn't
    // Unix output (avoids misparsing DOS/VMS lines).
    let lead = perms.chars().next()?;
    if !matches!(lead, 'd' | 'l' | '-' | 'b' | 'c' | 'p' | 's') || perms.len() < 10 {
        return None;
    }
    let kind = match lead {
        'd' => EntryKind::Directory,
        'l' => EntryKind::Symlink,
        _ => EntryKind::File,
    };
    let size: u64 = parts[4].parse().unwrap_or(0);
    let owner = parts[2].to_string();
    let modified = format!("{} {} {}", parts[5], parts[6], parts[7]);
    let name = parts[8..].join(" ");
    if name == "." || name == ".." {
        return None;
    }
    Some(DirEntry {
        path: join_path(parent, &name),
        name,
        kind,
        size,
        modified: Some(modified),
        permissions: Some(perms.to_string()),
        owner: Some(owner),
    })
}

/// Windows/DOS (IIS) format:
/// `12-05-96  05:03PM       <DIR>          folder`
/// `11-14-97  04:21PM                  953 file.txt`
fn parse_dos_line(line: &str, parent: &str) -> Option<DirEntry> {
    let parts: Vec<&str> = line.split_whitespace().collect();
    if parts.len() < 4 {
        return None;
    }
    // parts[0] = date (mm-dd-yy), parts[1] = time (hh:mmAM/PM).
    if !parts[0].contains('-') || !(parts[1].contains(':')) {
        return None;
    }
    let is_dir = parts[2].eq_ignore_ascii_case("<DIR>");
    let size: u64 = if is_dir { 0 } else { parts[2].parse().ok()? };
    let name = parts[3..].join(" ");
    if name == "." || name == ".." || name.is_empty() {
        return None;
    }
    Some(DirEntry {
        path: join_path(parent, &name),
        name,
        kind: if is_dir {
            EntryKind::Directory
        } else {
            EntryKind::File
        },
        size,
        modified: Some(format!("{} {}", parts[0], parts[1])),
        permissions: None,
        owner: None,
    })
}

/// OpenVMS format:
/// `FILE.TXT;1   18  21-MAR-2021 14:12 [GROUP,OWNER] (RWED,RWED,RE,)`
/// Directories appear as `NAME.DIR;1`.
fn parse_vms_line(line: &str, parent: &str) -> Option<DirEntry> {
    let parts: Vec<&str> = line.split_whitespace().collect();
    // Needs at least the versioned filename and a size column.
    if parts.len() < 2 {
        return None;
    }
    let first = parts[0];
    // VMS filenames carry a `;version` suffix - the strongest format signal.
    let (raw_name, _version) = first.split_once(';')?;
    if raw_name.is_empty() {
        return None;
    }
    let size: u64 = parts.get(1).and_then(|s| s.parse().ok()).unwrap_or(0);
    let is_dir = raw_name.to_ascii_uppercase().ends_with(".DIR");
    // Present directories without the `.DIR` suffix, matching how users navigate.
    let name = if is_dir {
        raw_name[..raw_name.len() - 4].to_string()
    } else {
        raw_name.to_string()
    };
    if name == "." || name == ".." {
        return None;
    }
    let modified = if parts.len() >= 4 {
        Some(format!("{} {}", parts[2], parts[3]))
    } else {
        None
    };
    Some(DirEntry {
        path: join_path(parent, &name),
        name,
        kind: if is_dir {
            EntryKind::Directory
        } else {
            EntryKind::File
        },
        size,
        modified,
        permissions: None,
        owner: None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::EntryKind;

    #[test]
    fn parses_unix_file_line() {
        let line = "-rw-r--r-- 1 john users 12600 May 10 08:11 styles.css";
        let e = parse_list_line(line, "/var/www").expect("should parse");
        assert_eq!(e.name, "styles.css");
        assert_eq!(e.path, "/var/www/styles.css");
        assert_eq!(e.size, 12600);
        assert!(matches!(e.kind, EntryKind::File));
        // ls -l columns: perms links OWNER group size month day time name
        assert_eq!(e.owner.as_deref(), Some("john"));
    }

    #[test]
    fn parses_directory_line() {
        let line = "drwxr-xr-x 2 john users 4096 May 09 06:23 images";
        let e = parse_list_line(line, "/var/www/").unwrap();
        assert_eq!(e.path, "/var/www/images");
        assert!(matches!(e.kind, EntryKind::Directory));
    }

    #[test]
    fn skips_dotdirs_and_malformed() {
        assert!(parse_list_line("drwxr-xr-x 2 j u 4096 May 09 06:23 .", "/x").is_none());
        assert!(parse_list_line("garbage", "/x").is_none());
    }

    #[test]
    fn parses_dos_lines() {
        let dir = parse_list_line("12-05-96  05:03PM       <DIR>          uploads", "/").unwrap();
        assert_eq!(dir.name, "uploads");
        assert!(matches!(dir.kind, EntryKind::Directory));
        assert_eq!(dir.size, 0);

        let file =
            parse_list_line("11-14-97  04:21PM                  953 index.htm", "/web").unwrap();
        assert_eq!(file.name, "index.htm");
        assert_eq!(file.path, "/web/index.htm");
        assert_eq!(file.size, 953);
        assert!(matches!(file.kind, EntryKind::File));
    }

    #[test]
    fn ftp_proxy_rewrites_username() {
        // No proxy → unchanged.
        assert_eq!(proxy_user("alice", "files.example.com", 21, false), "alice");
        // USER user@host style (default port omits the port).
        assert_eq!(
            proxy_user("alice", "files.example.com", 21, true),
            "alice@files.example.com"
        );
        // Non-default server port is appended.
        assert_eq!(
            proxy_user("alice", "files.example.com", 2121, true),
            "alice@files.example.com:2121"
        );
    }

    #[test]
    fn parses_vms_lines() {
        let file = parse_list_line(
            "LOGIN.COM;1   18  21-MAR-2021 14:12 [GRP,USER] (RWED,RWED,RE,)",
            "/SYS",
        )
        .unwrap();
        assert_eq!(file.name, "LOGIN.COM;1".split(';').next().unwrap());
        assert_eq!(file.name, "LOGIN.COM");
        assert_eq!(file.size, 18);
        assert!(matches!(file.kind, EntryKind::File));

        let dir = parse_list_line("PROJECTS.DIR;1   1  10-JAN-2020 09:00", "/DISK").unwrap();
        assert_eq!(dir.name, "PROJECTS");
        assert!(matches!(dir.kind, EntryKind::Directory));
    }

    #[test]
    fn auto_data_type_classifies_by_extension() {
        use suppaftp::types::FileType;
        // Text extensions → ASCII; everything else → binary.
        assert!(matches!(
            resolve_file_type(FtpDataType::Auto, "/srv/readme.txt", false),
            FileType::Ascii(_)
        ));
        assert!(matches!(
            resolve_file_type(FtpDataType::Auto, "/srv/photo.jpg", false),
            FileType::Binary
        ));
        // No extension defaults to binary (safe for unknown content).
        assert!(matches!(
            resolve_file_type(FtpDataType::Auto, "/srv/Makefile", false),
            FileType::Binary
        ));
        // Explicit modes override classification.
        assert!(matches!(
            resolve_file_type(FtpDataType::Ascii, "/srv/photo.jpg", false),
            FileType::Ascii(_)
        ));
        assert!(matches!(
            resolve_file_type(FtpDataType::Binary, "/srv/readme.txt", false),
            FileType::Binary
        ));
    }

    #[test]
    fn resume_forces_binary_even_for_ascii() {
        use suppaftp::types::FileType;
        // Resuming a text file must use binary so the byte offset stays valid.
        assert!(matches!(
            resolve_file_type(FtpDataType::Ascii, "/srv/readme.txt", true),
            FileType::Binary
        ));
        assert!(matches!(
            resolve_file_type(FtpDataType::Auto, "/srv/readme.txt", true),
            FileType::Binary
        ));
    }

    #[test]
    fn handles_names_with_spaces() {
        let line = "-rw-r--r-- 1 john users 10 May 10 08:11 my file.txt";
        let e = parse_list_line(line, "/x").unwrap();
        assert_eq!(e.name, "my file.txt");
    }
}
